### ISSUE TITLE
Update Post Error

### ISSUE THREAD

**Issue by Ocelottamer** [Harrilee/PigeonSale#3] opened 2021-11-14 07:49 UTC
Request: Use 'Put' method and Body (in json format) is:
                {
                    "post_id":"1",
                    "post_title":"My post",
                    "post_content":"contents!",
                    "post_status":"1",
                    "post_product_price":"100",
                    "post_images":[]
                }

All parameters are set here, but there's still an error, which is as follows:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/justin/Documents/GitHub/PigeonSale/backend/models/utils.py", line 71, in wrapper_user
    return func(*args)
  File "/Users/justin/Documents/GitHub/PigeonSale/backend/routes/posts.py", line 56, in update_post
    print(56, int(post.post_author_id) != postController.uid)
AttributeError: 'NoneType' object has no attribute 'post_author_id'

**Comment by Harrilee** [comment] 2021-11-14 10:34
the problem is caused by updating a non-existing post. it is fixed now

**Closed as completed** 2021-11-14 12:29 UTC
